version: 2
updates:
  # Gradle dependencies (version catalog: gradle/libs.versions.toml)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "gradle"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "org.jlleitschuh.gradle.ktlint"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      # Group PR for all FTC SDK dependencies
      ftc-sdk:
        patterns:
          - "org.firstinspires.ftc:*"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
